--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: images; Type: TABLE; Schema: public; Owner: photovault_usr
--

CREATE TABLE public.images (
    id bigint NOT NULL,
    content_type character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    file_path character varying(500) NOT NULL,
    file_size bigint NOT NULL,
    filename character varying(255) NOT NULL,
    is_archived boolean,
    is_deleted boolean,
    is_favorite boolean,
    original_filename character varying(255) NOT NULL,
    stored_filename character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    upload_date timestamp(6) without time zone,
    CONSTRAINT images_file_size_check CHECK ((file_size >= 1))
);


ALTER TABLE public.images OWNER TO photovault_usr;

--
-- Name: images_id_seq; Type: SEQUENCE; Schema: public; Owner: photovault_usr
--

ALTER TABLE public.images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: images; Type: TABLE DATA; Schema: public; Owner: photovault_usr
--

COPY public.images (id, content_type, created_at, file_path, file_size, filename, is_archived, is_deleted, is_favorite, original_filename, stored_filename, updated_at, upload_date) FROM stdin;
13	image/jpeg	2025-07-10 17:25:18.106536	/home/projs/Photovault/photovault-be/uploads/097d3395-a533-4f85-9b3f-e210c45c6ca3.jpg	123384	aworld.jpg	f	f	f	aworld.jpg	097d3395-a533-4f85-9b3f-e210c45c6ca3.jpg	2025-07-10 17:25:18.106563	2025-07-10 17:25:18.102983
14	image/jpeg	2025-07-10 17:25:18.118587	/home/projs/Photovault/photovault-be/uploads/571cb3e2-4ac3-4f35-a790-c65780cc7aa8.jpg	161724	datfile.jpg	f	f	f	datfile.jpg	571cb3e2-4ac3-4f35-a790-c65780cc7aa8.jpg	2025-07-10 17:25:18.11862	2025-07-10 17:25:18.116246
2	image/jpeg	2025-07-09 17:53:53.568655	/home/projs/Photovault/photovault-be/uploads/49acf43a-9f66-4feb-9da0-d84e48707892.jpg	3021918	Drive Art 2.jpg	f	f	f	Drive Art 2.jpg	49acf43a-9f66-4feb-9da0-d84e48707892.jpg	2025-07-09 17:53:53.568806	2025-07-09 17:53:53.547774
3	image/png	2025-07-10 01:29:13.860939	/home/projs/Photovault/photovault-be/uploads/5a733250-d392-4039-8373-22961194eb0c.png	7412189	Drive_3.png	f	f	f	Drive_3.png	5a733250-d392-4039-8373-22961194eb0c.png	2025-07-10 01:29:13.860962	2025-07-10 01:29:13.843521
4	image/jpeg	2025-07-10 01:29:28.745359	/home/projs/Photovault/photovault-be/uploads/00892fae-f6b5-4c02-9868-8d34aa68cd3a.jpg	4748566	Drive_4.jpg	f	f	f	Drive_4.jpg	00892fae-f6b5-4c02-9868-8d34aa68cd3a.jpg	2025-07-10 01:29:28.745366	2025-07-10 01:29:28.744727
15	image/jpeg	2025-07-10 17:25:18.13103	/home/projs/Photovault/photovault-be/uploads/d69f7a89-bd28-4b27-91c1-5ba4687e60ba.jpg	123301	excitingtime.jpg	f	f	f	excitingtime.jpg	d69f7a89-bd28-4b27-91c1-5ba4687e60ba.jpg	2025-07-10 17:25:18.131053	2025-07-10 17:25:18.129474
16	image/jpeg	2025-07-10 17:25:18.141977	/home/projs/Photovault/photovault-be/uploads/2c8b9775-7e13-40f6-afca-7341dc025c86.jpg	73475	hello_friend.jpg	f	f	f	hello_friend.jpg	2c8b9775-7e13-40f6-afca-7341dc025c86.jpg	2025-07-10 17:25:18.142013	2025-07-10 17:25:18.139772
17	image/jpeg	2025-07-10 17:25:18.151238	/home/projs/Photovault/photovault-be/uploads/9a271820-2b0c-45e6-b977-df83ac6a8ee5.jpg	107306	terminal.jpg	f	f	f	terminal.jpg	9a271820-2b0c-45e6-b977-df83ac6a8ee5.jpg	2025-07-10 17:25:18.151271	2025-07-10 17:25:18.149759
7	image/jpeg	2025-07-10 01:30:07.558172	/home/projs/Photovault/photovault-be/uploads/bc81d73a-83d5-41f6-ae92-39daec1e61b6.jpg	284307	Maus.jpg	f	f	f	Maus.jpg	bc81d73a-83d5-41f6-ae92-39daec1e61b6.jpg	2025-07-10 01:42:51.452315	2025-07-10 01:30:07.557126
8	image/jpeg	2025-07-10 02:21:27.498388	/home/projs/Photovault/photovault-be/uploads/0ab46322-8a02-49c8-966c-0ca1eea10c57.jpg	992104	Makarov Blueprint.jpg	f	f	f	Makarov Blueprint.jpg	0ab46322-8a02-49c8-966c-0ca1eea10c57.jpg	2025-07-10 02:21:27.498398	2025-07-10 02:21:27.496592
22	image/jpeg	2025-07-10 17:27:34.218998	/home/projs/Photovault/photovault-be/uploads/e041939f-4ef0-4cf3-bb66-922b1f4873c3.jpg	49627	wp4507700-mr-robot-wallpapers.jpg	f	f	f	wp4507700-mr-robot-wallpapers.jpg	e041939f-4ef0-4cf3-bb66-922b1f4873c3.jpg	2025-07-10 17:27:34.219014	2025-07-10 17:27:34.218049
19	image/jpeg	2025-07-10 17:25:18.174306	/home/projs/Photovault/photovault-be/uploads/d23ce9f3-f669-42d8-a51c-94ff9e37fdf0.jpg	49627	wp4507700-mr-robot-wallpapers.jpg	f	t	f	wp4507700-mr-robot-wallpapers.jpg	d23ce9f3-f669-42d8-a51c-94ff9e37fdf0.jpg	2025-07-10 17:27:47.707269	2025-07-10 17:25:18.173057
23	image/jpeg	2025-07-10 17:28:18.894565	/home/projs/Photovault/photovault-be/uploads/20fe3bb2-9b06-45da-8f6c-b46db1932e4f.jpg	3361622	Drive Art.jpg	f	f	f	Drive Art.jpg	20fe3bb2-9b06-45da-8f6c-b46db1932e4f.jpg	2025-07-10 17:28:18.894614	2025-07-10 17:28:18.890089
9	image/jpeg	2025-07-10 02:21:32.676622	/home/projs/Photovault/photovault-be/uploads/57f894ff-52c5-47b9-a65b-58745dd17d02.jpg	723634	1911.jpg	f	t	f	1911.jpg	57f894ff-52c5-47b9-a65b-58745dd17d02.jpg	2025-07-10 02:21:53.028901	2025-07-10 02:21:32.675992
6	image/gif	2025-07-10 01:29:59.901082	/home/projs/Photovault/photovault-be/uploads/3a905baf-8a98-463f-8035-7ea2b0dbbb43.gif	741935	P40.gif	t	f	t	P40.gif	3a905baf-8a98-463f-8035-7ea2b0dbbb43.gif	2025-07-10 02:22:49.775955	2025-07-10 01:29:59.899399
5	image/jpeg	2025-07-10 01:29:46.788647	/home/projs/Photovault/photovault-be/uploads/141f71ff-f90b-4757-a4ac-061521777702.jpg	6461448	Mustang Blueprint.jpg	f	f	t	Mustang Blueprint.jpg	141f71ff-f90b-4757-a4ac-061521777702.jpg	2025-07-10 02:23:45.404474	2025-07-10 01:29:46.787809
10	image/jpeg	2025-07-10 02:46:06.415635	/home/projs/Photovault/photovault-be/uploads/ef4c2f9a-a76f-48ac-9420-00a1169a964f.jpg	404050	1228789.jpg	f	f	f	1228789.jpg	ef4c2f9a-a76f-48ac-9420-00a1169a964f.jpg	2025-07-10 02:46:06.415651	2025-07-10 02:46:06.413316
12	image/png	2025-07-10 17:04:43.676901	/home/projs/Photovault/photovault-be/uploads/828c51ad-5c19-4f20-8f52-dd723b241761.png	1681378	vlcsnap-2025-06-21-14h18m39s655.png	f	f	f	vlcsnap-2025-06-21-14h18m39s655.png	828c51ad-5c19-4f20-8f52-dd723b241761.png	2025-07-10 17:04:43.676927	2025-07-10 17:04:43.674903
24	image/jpeg	2025-07-10 17:28:18.910283	/home/projs/Photovault/photovault-be/uploads/346d0cd6-37cb-47cb-844d-3fd4cfbcc21e.jpg	69310	Drive_1.jpg	f	f	f	Drive_1.jpg	346d0cd6-37cb-47cb-844d-3fd4cfbcc21e.jpg	2025-07-10 17:28:18.910309	2025-07-10 17:28:18.908697
25	image/jpeg	2025-07-10 17:28:18.939294	/home/projs/Photovault/photovault-be/uploads/6d9ec67c-2ac5-4b5f-b0d6-dfb4ca3ff825.jpg	4748566	Drive_4.jpg	f	f	f	Drive_4.jpg	6d9ec67c-2ac5-4b5f-b0d6-dfb4ca3ff825.jpg	2025-07-10 17:28:18.93932	2025-07-10 17:28:18.9377
26	image/jpeg	2025-07-10 17:28:18.949709	/home/projs/Photovault/photovault-be/uploads/5135b652-974b-4285-9505-c075740375eb.jpg	300616	I drive.jpg	f	f	f	I drive.jpg	5135b652-974b-4285-9505-c075740375eb.jpg	2025-07-10 17:28:18.949732	2025-07-10 17:28:18.948215
21	image/jpeg	2025-07-10 17:27:34.213924	/home/projs/Photovault/photovault-be/uploads/93342ec8-66fe-4fe8-a607-acdeae37db24.jpg	164893	wallpaperflare.com_wallpaper.jpg	f	t	f	wallpaperflare.com_wallpaper.jpg	93342ec8-66fe-4fe8-a607-acdeae37db24.jpg	2025-07-11 13:39:47.197576	2025-07-10 17:27:34.212949
11	image/jpeg	2025-07-10 17:04:43.545124	/home/projs/Photovault/photovault-be/uploads/efc971d5-b3d6-419b-8537-9a5f8095ef19.jpg	2785489	PXL_20250302_044754074.jpg	f	t	f	PXL_20250302_044754074.jpg	efc971d5-b3d6-419b-8537-9a5f8095ef19.jpg	2025-07-11 13:39:54.966217	2025-07-10 17:04:43.489655
28	image/png	2025-07-11 13:40:53.938136	/home/projs/Photovault/photovault-be/uploads/7376f3b5-aebb-47dc-8262-cf3f3dd94deb.png	124327	Screenshot_20250707_142416.png	f	f	f	Screenshot_20250707_142416.png	7376f3b5-aebb-47dc-8262-cf3f3dd94deb.png	2025-07-11 13:40:53.938164	2025-07-11 13:40:53.936706
29	image/png	2025-07-11 13:40:53.945396	/home/projs/Photovault/photovault-be/uploads/a9fd16ba-a6d0-49b1-bcfe-37ac9e5c637b.png	11461	Screenshot_20250707_221244.png	f	f	f	Screenshot_20250707_221244.png	a9fd16ba-a6d0-49b1-bcfe-37ac9e5c637b.png	2025-07-11 13:40:53.945413	2025-07-11 13:40:53.944159
30	image/png	2025-07-11 13:40:53.953344	/home/projs/Photovault/photovault-be/uploads/d8989861-56ff-4f90-9974-05d20f66ab88.png	535683	Screenshot_20250706_104207.png	f	f	f	Screenshot_20250706_104207.png	d8989861-56ff-4f90-9974-05d20f66ab88.png	2025-07-11 13:40:53.953359	2025-07-11 13:40:53.952201
31	image/png	2025-07-11 13:40:53.959115	/home/projs/Photovault/photovault-be/uploads/b529b2e6-08b5-4370-ae74-6426a0528897.png	81656	Screenshot_20250703_010928.png	f	f	f	Screenshot_20250703_010928.png	b529b2e6-08b5-4370-ae74-6426a0528897.png	2025-07-11 13:40:53.959135	2025-07-11 13:40:53.958129
27	image/png	2025-07-11 13:40:53.896117	/home/projs/Photovault/photovault-be/uploads/dbf09263-322e-496d-9f4f-f8035cf3b7d6.png	82339	Screenshot_20250707_001028.png	f	t	f	Screenshot_20250707_001028.png	dbf09263-322e-496d-9f4f-f8035cf3b7d6.png	2025-07-11 13:41:01.997061	2025-07-11 13:40:53.889394
33	image/png	2025-07-11 13:40:53.974903	/home/projs/Photovault/photovault-be/uploads/6915420b-899e-4585-aa35-6bc78964f27e.png	72252	Screenshot_20250702_191119.png	f	f	f	Screenshot_20250702_191119.png	6915420b-899e-4585-aa35-6bc78964f27e.png	2025-07-11 13:40:53.974925	2025-07-11 13:40:53.973857
36	image/png	2025-07-11 13:40:53.997215	/home/projs/Photovault/photovault-be/uploads/4b7675be-0698-4da3-ad99-034e8f64d66f.png	559733	Screenshot_20250701_235016.png	f	f	f	Screenshot_20250701_235016.png	4b7675be-0698-4da3-ad99-034e8f64d66f.png	2025-07-11 13:40:53.997231	2025-07-11 13:40:53.996084
34	image/png	2025-07-11 13:40:53.982123	/home/projs/Photovault/photovault-be/uploads/51bb4d11-334f-402f-bae5-a9109f71e648.png	56590	Screenshot_20250701_203450.png	f	t	f	Screenshot_20250701_203450.png	51bb4d11-334f-402f-bae5-a9109f71e648.png	2025-07-11 13:41:29.431134	2025-07-11 13:40:53.980188
35	image/png	2025-07-11 13:40:53.988606	/home/projs/Photovault/photovault-be/uploads/afe5f8ed-dd45-453a-8de1-a6b2edb1a3f6.png	66669	Screenshot_20250701_203626.png	f	f	t	Screenshot_20250701_203626.png	afe5f8ed-dd45-453a-8de1-a6b2edb1a3f6.png	2025-07-11 13:42:15.347644	2025-07-11 13:40:53.987489
32	image/png	2025-07-11 13:40:53.967957	/home/projs/Photovault/photovault-be/uploads/9e220395-5fd7-42cc-98fb-29d246150243.png	334135	Screenshot_20250702_191213.png	f	f	t	Screenshot_20250702_191213.png	9e220395-5fd7-42cc-98fb-29d246150243.png	2025-07-11 13:42:17.661961	2025-07-11 13:40:53.966634
37	image/png	2025-07-11 13:53:37.54473	/home/projs/Photovault/photovault-be/uploads/deb8a75c-9025-4b05-bc6b-e14a94c8bcaa.png	153685	Screenshot_20250702_191117.png	f	f	f	Screenshot_20250702_191117.png	deb8a75c-9025-4b05-bc6b-e14a94c8bcaa.png	2025-07-11 13:53:37.544746	2025-07-11 13:53:37.542917
38	image/png	2025-07-11 13:53:37.555749	/home/projs/Photovault/photovault-be/uploads/f31ddc68-30fb-47dd-abc0-dec6e84eff20.png	81656	Screenshot_20250703_010928.png	f	f	f	Screenshot_20250703_010928.png	f31ddc68-30fb-47dd-abc0-dec6e84eff20.png	2025-07-11 13:53:37.555759	2025-07-11 13:53:37.555183
39	image/png	2025-07-11 13:53:37.560319	/home/projs/Photovault/photovault-be/uploads/4cd9eca2-79d6-4f12-9dd2-07a75cdad4fe.png	585005	Screenshot_20250704_015854.png	f	f	f	Screenshot_20250704_015854.png	4cd9eca2-79d6-4f12-9dd2-07a75cdad4fe.png	2025-07-11 13:53:37.560329	2025-07-11 13:53:37.559693
40	image/png	2025-07-11 13:53:37.56406	/home/projs/Photovault/photovault-be/uploads/02c6cd80-257f-4efe-9cac-d0965dd66e88.png	87565	Screenshot_20250703_171102.png	f	f	f	Screenshot_20250703_171102.png	02c6cd80-257f-4efe-9cac-d0965dd66e88.png	2025-07-11 13:53:37.564071	2025-07-11 13:53:37.563412
41	image/png	2025-07-11 13:53:37.586866	/home/projs/Photovault/photovault-be/uploads/b977d799-7cfc-4e02-93f2-acf2f9670404.png	8311844	Screenshot_20250708_194654.png	f	f	f	Screenshot_20250708_194654.png	b977d799-7cfc-4e02-93f2-acf2f9670404.png	2025-07-11 13:53:37.586885	2025-07-11 13:53:37.586106
\.


--
-- Name: images_id_seq; Type: SEQUENCE SET; Schema: public; Owner: photovault_usr
--

SELECT pg_catalog.setval('public.images_id_seq', 42, true);


--
-- Name: images images_pkey; Type: CONSTRAINT; Schema: public; Owner: photovault_usr
--

ALTER TABLE ONLY public.images
    ADD CONSTRAINT images_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

