spring.application.name=photovault
# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/photovault_db
spring.datasource.username=postgres
spring.datasource.password=hm102499@#

# JPA/Hibernate Configuration
# This tells Hibernate to update the database schema based on your code (great for development)
spring.jpa.hibernate.ddl-auto=update

#Actuator support
management.endpoints.web.exposure.include=*


# This makes the actual SQL queries visible in your console logs (invaluable for debugging)
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

#Dir for uploading images
file.storage.location=/home/conquer0r/photovault_uploads

# Multipart File Size Configuration
# Set the maximum size for a single file to 10 megabytes
spring.servlet.multipart.max-file-size=10MB
# Set the maximum size for an entire request (can include multiple files)
spring.servlet.multipart.max-request-size=10MB
